## Evaluación Final Módulo 3

In [1]:
# Nos importamos todas las librerías que necesitaremos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Cargamos los csv con los datos y vemos las primeras líneas (también se podría ver el final o un sample)
df_vuelos = pd.read_csv("Customer Flight Activity.csv", index_col=0)

df_vuelos.head()

Year  Month  Flights Booked  Flights with Companions  \
Loyalty Number                                                         
100018          2017      1               3                        0   
100102          2017      1              10                        4   
100140          2017      1               6                        0   
100214          2017      1               0                        0   
100272          2017      1               0                        0   

                Total Flights  Distance  Points Accumulated  Points Redeemed  \
Loyalty Number                                                                 
100018                      3      1521               152.0                0   
100102                     14      2030               203.0                0   
100140                      6      1200               120.0                0   
100214                      0         0                 0.0                0   
100272                      0         0                 0.0                0   

                Dollar Cost Points Redeemed  
Loyalty Number                               
100018                                    0  
100102                                    0  
100140                                    0  
100214                                    0  
100272                                    0

1. Exploración

In [4]:
df_clientes = pd.read_csv("Customer Loyalty History.csv", index_col=0)

df_clientes.head()

Country          Province       City Postal Code  Gender  \
Loyalty Number                                                            
480934          Canada           Ontario    Toronto     M2Z 4K1  Female   
549612          Canada           Alberta   Edmonton     T3G 6Y6    Male   
429460          Canada  British Columbia  Vancouver     V6E 3D9    Male   
608370          Canada           Ontario    Toronto     P1W 1K4    Male   
530508          Canada            Quebec       Hull     J8Y 3Z5    Male   

               Education    Salary Marital Status Loyalty Card      CLV  \
Loyalty Number                                                            
480934          Bachelor   83236.0        Married         Star  3839.14   
549612           College       NaN       Divorced         Star  3839.61   
429460           College       NaN         Single         Star  3839.75   
608370           College       NaN         Single         Star  3839.75   
530508          Bachelor  103495.0        Married         Star  3842.79   

               Enrollment Type  Enrollment Year  Enrollment Month  \
Loyalty Number                                                      
480934                Standard             2016                 2   
549612                Standard             2016                 3   
429460                Standard             2014                 7   
608370                Standard             2013                 2   
530508                Standard             2014                10   

                Cancellation Year  Cancellation Month  
Loyalty Number                                         
480934                        NaN                 NaN  
549612                        NaN                 NaN  
429460                     2018.0                 1.0  
608370                        NaN                 NaN  
530508                        NaN                 NaN

In [ ]:
#Sacamos la info para una exploración básica general: columnas, cantidad de filas, de nulos y el tipo de dato en cada columna.
df_vuelos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 405624 entries, 100018 to 999986
Data columns (total 9 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   Year                         405624 non-null  int64  
 1   Month                        405624 non-null  int64  
 2   Flights Booked               405624 non-null  int64  
 3   Flights with Companions      405624 non-null  int64  
 4   Total Flights                405624 non-null  int64  
 5   Distance                     405624 non-null  int64  
 6   Points Accumulated           405624 non-null  float64
 7   Points Redeemed              405624 non-null  int64  
 8   Dollar Cost Points Redeemed  405624 non-null  int64  
dtypes: float64(1), int64(8)
memory usage: 30.9 MB


In [6]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16737 entries, 480934 to 652627
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Country             16737 non-null  object 
 1   Province            16737 non-null  object 
 2   City                16737 non-null  object 
 3   Postal Code         16737 non-null  object 
 4   Gender              16737 non-null  object 
 5   Education           16737 non-null  object 
 6   Salary              12499 non-null  float64
 7   Marital Status      16737 non-null  object 
 8   Loyalty Card        16737 non-null  object 
 9   CLV                 16737 non-null  float64
 10  Enrollment Type     16737 non-null  object 
 11  Enrollment Year     16737 non-null  int64  
 12  Enrollment Month    16737 non-null  int64  
 13  Cancellation Year   2067 non-null   float64
 14  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(2), object(9)
memory usage: 2.0

In [ ]:
# Vemos si hay nulos y dónde están
df_clientes.isnull().sum()

Country                   0
Province                  0
City                      0
Postal Code               0
Gender                    0
Education                 0
Salary                 4238
Marital Status            0
Loyalty Card              0
CLV                       0
Enrollment Type           0
Enrollment Year           0
Enrollment Month          0
Cancellation Year     14670
Cancellation Month    14670
dtype: int64

In [16]:
df_vuelos.isnull().sum()

Year                           0
Month                          0
Flights Booked                 0
Flights with Companions        0
Total Flights                  0
Distance                       0
Points Accumulated             0
Points Redeemed                0
Dollar Cost Points Redeemed    0
dtype: int64

In [17]:
# Identificamos los valores únicos en todas las columnas para detectar inconsistencias o errores tipográficos.
for columna in df_vuelos:
    print(f'La columna {columna} tiene estos valores únicos:')
    print(df_vuelos[columna].unique())
    print('----------------------------') 

La columna Year tiene estos valores únicos:
[2017 2018]
----------------------------
La columna Month tiene estos valores únicos:
[ 1  9  2  3 11  4  5  7  6  8 10 12]
----------------------------
La columna Flights Booked tiene estos valores únicos:
[ 3 10  6  0  8 11  9  4  7  5  2  1 12 13 14 16 15 17 18 19 20 21]
----------------------------
La columna Flights with Companions tiene estos valores únicos:
[ 0  4  7  1  6  3  5  2 10  8  9 11]
----------------------------
La columna Total Flights tiene estos valores únicos:
[ 3 14  6  0 15 11 12 10  8  9  7  5 16  2  1 17 13 22  4 19 18 21 26 20
 23 25 27 24 28 30 29 31 32]
----------------------------
La columna Distance tiene estos valores únicos:
[1521 2030 1200 ... 1217  617 4135]
----------------------------
La columna Points Accumulated tiene estos valores únicos:
[152.   203.   120.   ...  18.75 601.   626.  ]
----------------------------
La columna Points Redeemed tiene estos valores únicos:
[  0 341 364 310 445 312 343 366 38

In [19]:
# Como en dos columnas no se ven todos los datos únicos, buscamos si hay valores negativos

for columna in df_vuelos.select_dtypes(include=['int64', 'float64']).columns:
    negativos = df_vuelos[df_vuelos[columna] < 0]
    if not negativos.empty:
        print(f"\nColumna: '{columna}'")
        print(f"Cantidad de valores negativos: {len(negativos)}")
        print(negativos)
    else:
        print(f"\nColumna: '{columna}' - No hay valores negativos")


Columna: 'Year' - No hay valores negativos

Columna: 'Month' - No hay valores negativos

Columna: 'Flights Booked' - No hay valores negativos

Columna: 'Flights with Companions' - No hay valores negativos

Columna: 'Total Flights' - No hay valores negativos

Columna: 'Distance' - No hay valores negativos

Columna: 'Points Accumulated' - No hay valores negativos

Columna: 'Points Redeemed' - No hay valores negativos

Columna: 'Dollar Cost Points Redeemed' - No hay valores negativos


In [20]:
# Hacemos lo mismo con el otro df
for columna in df_clientes:
    print(f'La columna {columna} tiene estos valores únicos:')
    print(df_clientes[columna].unique())
    print('----------------------------') 

La columna Country tiene estos valores únicos:
['Canada']
----------------------------
La columna Province tiene estos valores únicos:
['Ontario' 'Alberta' 'British Columbia' 'Quebec' 'Yukon' 'New Brunswick'
 'Manitoba' 'Nova Scotia' 'Saskatchewan' 'Newfoundland'
 'Prince Edward Island']
----------------------------
La columna City tiene estos valores únicos:
['Toronto' 'Edmonton' 'Vancouver' 'Hull' 'Whitehorse' 'Trenton' 'Montreal'
 'Dawson Creek' 'Quebec City' 'Fredericton' 'Ottawa' 'Tremblant' 'Calgary'
 'Thunder Bay' 'Whistler' 'Peace River' 'Winnipeg' 'Sudbury'
 'West Vancouver' 'Halifax' 'London' 'Regina' 'Kelowna' "St. John's"
 'Victoria' 'Kingston' 'Banff' 'Moncton' 'Charlottetown']
----------------------------
La columna Postal Code tiene estos valores únicos:
['M2Z 4K1' 'T3G 6Y6' 'V6E 3D9' 'P1W 1K4' 'J8Y 3Z5' 'Y2K 6R0' 'P5S 6R4'
 'K8V 4B2' 'H2Y 2W2' 'M8Y 4K8' 'U5I 4F1' 'G1B 3L5' 'H4G 3T4' 'M2M 7K8'
 'M2M 6J7' 'E3B 2H2' 'M1R 4K3' 'T9G 1W3' 'H2Y 4R4' 'V5R 1W3' 'P1L 8X8'
 'K1F 2

In [23]:
# Buscamos los valores negativos, pero SOLO en las columnas numéricas, para eso hacemos una variable 
columnas_numericas_clientes = df_clientes.select_dtypes(include=['int64', 'float64']).columns

for columna in columnas_numericas_clientes:
    negativos = df_clientes[df_clientes[columna] < 0]
    if not negativos.empty:
        print(f"OJO columna: {columna}")
        print(f"Cantidad de valores negativos: {len(negativos)}")
    else:
        print(f"Columna: {columna} - No hay valores negativos")

OJO columna: Salary
Cantidad de valores negativos: 20
Columna: CLV - No hay valores negativos
Columna: Enrollment Year - No hay valores negativos
Columna: Enrollment Month - No hay valores negativos
Columna: Cancellation Year - No hay valores negativos
Columna: Cancellation Month - No hay valores negativos


In [25]:
# Vemos en detalle los negativos de salary
df_clientes[df_clientes['Salary'] < 0][['Country', 'Province', 'Salary']]

Country          Province   Salary
Loyalty Number                                   
542976          Canada            Quebec -49830.0
959977          Canada  British Columbia -12497.0
232755          Canada  British Columbia -46683.0
525245          Canada  British Columbia -45962.0
603070          Canada  British Columbia -19325.0
491242          Canada  British Columbia -43234.0
115505          Canada      Newfoundland -10605.0
430398          Canada      Newfoundland -17534.0
152016          Canada           Ontario -58486.0
194065          Canada           Ontario -31911.0
212128          Canada           Ontario -49001.0
790475          Canada           Ontario -34079.0
366599          Canada           Ontario  -9081.0
436087          Canada            Quebec -46470.0
364596          Canada            Quebec -26322.0
239955          Canada            Quebec -47310.0
347013          Canada            Quebec -39503.0
729561          Canada            Quebec -19332.0
734647          Canada      Saskatchewan -46303.0
906428          Canada             Yukon -57297.0

In [26]:
# Verificamos si hay duplicados
df_clientes.duplicated().sum()

0

In [ ]:
df_vuelos.duplicated().sum() # Aquí hay duplicados pero entendemos que cada cliente vuela varias veces, por eso hay varios registros

228705

In [32]:
# Agrupar por cliente + año + mes y contar registros
resumen_vuelos = df_vuelos.groupby(['Loyalty Number', 'Year', 'Month']).size().reset_index(name='Conteo')
resumen_vuelos.sort_values('Conteo', ascending=False)

Loyalty Number  Year  Month  Conteo
258415          678205  2017      8       3
258410          678205  2017      3       3
258430          678205  2018     11       3
258429          678205  2018     10       3
258428          678205  2018      9       3
...                ...   ...    ...     ...
134421          403052  2018     10       1
134420          403052  2018      9       1
134419          403052  2018      8       1
134418          403052  2018      7       1
401687          999986  2018     12       1

[401688 rows x 4 columns]

In [33]:
# Agrupar por cliente + año + mes y contar registros
resumen_vuelos = df_vuelos.groupby(['Loyalty Number', 'Year', 'Month']).size().reset_index(name='Conteo')
resumen_vuelos.sort_values('Conteo', ascending=False).head()

Loyalty Number  Year  Month  Conteo
258415          678205  2017      8       3
258410          678205  2017      3       3
258430          678205  2018     11       3
258429          678205  2018     10       3
258428          678205  2018      9       3

2. Limpieza.